### ISSUE TITLE
Pronouns - Annuler json error

### ISSUE THREAD

**Issue by Eccleria** [Eccleria/ewibot#107]
```javascript
file:///home/ewibot/ewibot/src/admin/pronouns.js:27
  if (json[1] !== "Annuler") {
          ^

TypeError: Cannot read properties of undefined (reading '1')
    at buttonHandler (file:///home/ewibot/ewibot/src/admin/pronouns.js:27:11)
    at Client.onInteractionCreate (file:///home/ewibot/ewibot/src/admin/listeners.js:38:5)
    at Client.emit (node:events:527:28)
    at InteractionCreateAction.handle (/home/ewibot/ewibot/node_modules/discord.js/src/client/actions/InteractionCreate.js:83:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/home/ewibot/ewibot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)
```

**Comment by Eccleria** [comment]
No reason from tests, maybe Internet issue
