### ISSUE TITLE
Discord.js TypeError - channel.isText is not a function

### ISSUE THREAD

**Issue by Eccleria** [Eccleria/ewibot#173]
```js
/home/ewibot/ewibot/node_modules/discord.js/src/client/actions/InteractionCreate.js:48
        if (channel && !channel.isText()) return;
                                ^

TypeError: channel.isText is not a function
    at InteractionCreateAction.handle (/home/ewibot/ewibot/node_modules/discord.js/src/client/actions/InteractionCreate.js:48:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/home/ewibot/ewibot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/ewibot/ewibot/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/ewibot/ewibot/node_modules/ws/lib/receiver.js:528:14)
    ```

**Comment by Eccleria** [comment]
Apparently caused by Discord change to interactions
Fixed in https://github.com/discordjs/discord.js/pull/9203

**Comment by Eccleria** [comment]
```js
/home/ewibot/ewibot/node_modules/discord.js/src/client/actions/InteractionCreate.js:48
        if (channel && !channel.isText()) return;
                                ^

TypeError: channel.isText is not a function
    at InteractionCreateAction.handle (/home/ewibot/ewibot/node_modules/discord.js/src/client/actions/InteractionCreate.js:48:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/home/ewibot/ewibot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/home/ewibot/ewibot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/ewibot/ewibot/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/ewibot/ewibot/node_modules/ws/lib/receiver.js:528:14)
    ```

Should now follow the alternatives suggested in Discord.js Discord server FAQ channel

**Comment by Eccleria** [comment]
Was fixed in prod by updating yarn packages
