### ISSUE TITLE
Update-Fix/Polls

### ISSUE THREAD

**Issue by Eccleria** [Eccleria/ewibot#239]

**Comment by Eccleria** [comment]
```js
components[0].components[2].emoji.name: Invalid emoji
    at RequestHandler.execute (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async MessageManager.edit (/home/ewibot/ewibot/node_modules/discord.js/src/managers/MessageManager.js:132:15) {
  method: 'patch',
  path: '/channels/822132004581408828/messages/1136719598297829486',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [
        {
          title: 'Ecclé est-il un génial développeur ?',
          type: 'rich',
          description: "un sondage qu'il est important",
          url: null,
          timestamp: 2023-08-03T17:57:51.313Z,
          color: 1146986,
          fields: [ [Object], [Object], [Object] ],
          thumbnail: null,
          image: null,
          author: null,
          footer: { text: 'Vote unique | ⚙️ options', icon_url: undefined }
        }
      ],
      components: [
        {
          components: [ [Object], [Object], [Object], [Object] ],
          type: 1
        }
      ],
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: 0,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    },
    files: []
  }
}
```

**Comment by Eccleria** [comment]
```js
file:///home/ewibot/ewibot/src/commands/polls/pollsUtils.js:110
  const values = dbPoll.votes.map((obj) => obj.votes.length);
                        ^

TypeError: Cannot read properties of undefined (reading 'votes')
    at refreshPollFields (file:///home/ewibot/ewibot/src/commands/polls/pollsUtils.js:110:25)
    at stopPoll (file:///home/ewibot/ewibot/src/commands/polls/pollsUtils.js:175:21)
    at stopPollButtonAction (file:///home/ewibot/ewibot/src/commands/polls/pollsButton.js:80:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Eccleria** [comment]
- [ ] add a reminder 1h before the timeout end

**Comment by Eccleria** [comment]
- [ ] update 2nd embed if current time is different from planned ending time

**Comment by Eccleria** [comment]
- [ ] send results in ending message

**Comment by Eccleria** [comment]
- [ ] Change the colour of winning choices on poll results
