### ISSUE TITLE
Fix Polls - invalid `emoteColor` count value

### ISSUE THREAD

**Issue by Eccleria** [Eccleria/ewibot#272]
```js
file:///home/ewibot/ewibot/src/commands/polls/pollsVote.js:130
      emoteColor.repeat(nb) +
                 ^

RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at file:///home/ewibot/ewibot/src/commands/polls/pollsVote.js:130:18
    at Array.reduce (<anonymous>)
    at pollVoteHandler (file:///home/ewibot/ewibot/src/commands/polls/pollsVote.js:124:31)
    at voteButtonHandler (file:///home/ewibot/ewibot/src/commands/polls/pollsHandlers.js:43:11)
    at pollsButtonHandler (file:///home/ewibot/ewibot/src/commands/polls/pollsHandlers.js:21:29)
    at Timeout.pollBufferLoop [as _onTimeout] (file:///home/ewibot/ewibot/src/commands/polls/pollsCollectors.js:41:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Eccleria** [comment]
```js
file:///home/ewibot/ewibot/src/commands/polls/pollsVote.js:131
      emoteColor.repeat(nb) +
                 ^

RangeError: Invalid count value: -1
    at String.repeat (<anonymous>)
    at file:///home/ewibot/ewibot/src/commands/polls/pollsVote.js:131:18
    at Array.reduce (<anonymous>)
    at pollVoteHandler (file:///home/ewibot/ewibot/src/commands/polls/pollsVote.js:125:31)
    at voteButtonHandler (file:///home/ewibot/ewibot/src/commands/polls/pollsHandlers.js:42:11)
    at pollsButtonHandler (file:///home/ewibot/ewibot/src/commands/polls/pollsHandlers.js:20:29)
    at Timeout.pollBufferLoop [as _onTimeout] (file:///home/ewibot/ewibot/src/commands/polls/pollsCollectors.js:49:13)
    at listOnTimeout (node:internal/timers:583:11)
    at process.processTimers (node:internal/timers:519:7)
```
