### ISSUE TITLE
Timeout - Invalid Form Body

### ISSUE THREAD

**Issue by Eccleria** [Eccleria/ewibot#306]
```js
DiscordAPIError[50035]: Invalid Form Body
communication_disabled_until[INVALID_COMMUNICATION_DISABLED_TIMESTAMP]: Invalid communication disabled timestamp
    at handleErrors (/home/ewibot/ewibot/node_modules/@discordjs/rest/dist/index.js:640:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (/home/ewibot/ewibot/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/home/ewibot/ewibot/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/home/ewibot/ewibot/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async GuildMemberManager.edit (/home/ewibot/ewibot/node_modules/discord.js/src/managers/GuildMemberManager.js:381:15)
    at async Object.action (file:///home/ewibot/ewibot/src/commands/timeout.js:109:5) {
  requestBody: {
    files: undefined,
    json: {
      communicationDisabledUntil: [M],
      communication_disabled_until: '2024-04-24T21:14:41.654Z'
    }
  },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { communication_disabled_until: [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PATCH',
  url: 'https://discord.com/api/v10/guilds/816961245743808582/members/311822906659307520'
}
```

**Comment by Eccleria** [comment]
It might be caused by the timer limit value of `2147483647` ms
