### ISSUE TITLE
Admin_logs channelUpdate embed field length error

### ISSUE THREAD

**Issue by Eccleria** [Eccleria/ewibot#84]
```javascript
finishEmbed error
 Salon modifié DiscordAPIError: Invalid Form Body
embeds[0].fields[2].value: Must be 1024 or fewer in length.
    at RequestHandler.execute (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/home/ewibot/ewibot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15)
    at async finishEmbed (file:///home/ewibot/ewibot/src/admin/utils.js:122:21) {
  method: 'post',
  path: '/channels/959168176908804106/messages',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [Array],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

- [ ] handle similar channels at same level
- [ ] handle string > 1024

**Comment by Eccleria** [comment]
might be fixed by #180
